"""R3 for this corpus: generation adds, and edits only what was declared.

⛔ Generated by studyforge onboarding. A hand-edit here is a finding
against that skill rather than a fix (R19); change corpus.json and
regenerate.
"""

from __future__ import annotations

import pathlib
import shutil
import subprocess

import pytest


#: Every path this corpus declared in permitted_edits, taken from
#: corpus.json. An edit to anything else is what this test catches.
PERMITTED = []


def test_generation_is_non_destructive():
    """Nothing existing is changed that the manifest did not declare."""
    git = shutil.which('git')
    if git is None:
        pytest.skip('git is not installed, so the working tree cannot be read')
    root = pathlib.Path(__file__).resolve().parent.parent
    result = subprocess.run(
        [git, 'status', '--porcelain', '-z'],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        pytest.skip('not a git working tree, so there is nothing to compare with')
    changed = [
        entry[3:]
        for entry in result.stdout.split(chr(0))
        if entry and not entry.startswith('??')
    ]
    undeclared = sorted(set(changed) - set(PERMITTED))
    assert not undeclared, (
        'generation is additive (R3); these existing files changed and '
        'the manifest declares no edit to them: ' + repr(undeclared)
    )
