"""R3 for this corpus: generation adds, and edits only what was declared.

Read twice — from what a build DECLARES it writes, which no working-tree
state can move, and from the tree itself, where an addition is never a
breach and a rewrite must be declared.

⛔ Generated by studyforge onboarding. A hand-edit here is a finding
against that skill rather than a fix (R19); change corpus.json and
regenerate.
"""

from __future__ import annotations

import pathlib
import shutil
import subprocess

import pytest

from studyforge.cli.plan import plan_for
from studyforge.corpus.manifest import MANIFEST_FILENAME, parse
from studyforge.corpus.manifest.edits import reads_as_content
from studyforge.skills.reconnaissance.installed import generated


#: Every path this corpus declared in permitted_edits, taken from
#: corpus.json at the run that generated this file. An edit to anything
#: else is what this check catches — and the corpus is asked below
#: whether this is still its own declaration (R19).
PERMITTED = []

#: What a status letter says about a file that ALREADY EXISTED:
#: a rewrite, a type change, a removal, an unmerged path.
CHANGED = ('M', 'T', 'D', 'U')

#: The status letters whose record carries a SECOND path: with -z the
#: origin arrives as its own NUL-separated field, so it is consumed
#: rather than read as another record.
WITH_ORIGIN = ('R', 'C')

#: The one of those two where the origin is a path that MOVED. A copy
#: leaves its origin exactly as it was, so a copy is an addition.
MOVED = 'R'

#: The framework's own directory at the corpus root. ⛔ Not a guess:
#: validate.source.SKIP_DIRS declares it this tool's and never the
#: corpus's material, so what changes inside it is the framework's own
#: writing — the narration record, the site cache, the pin.
FRAMEWORK_DIR = '.studyforge/'

#: Said, never assumed, when the plan will not say what a build writes.
UNPLANNABLE = (
    'the plan for this corpus refused, so what a build writes into it '
    'cannot be read and R3 cannot be checked against it: '
)


def _root():
    """The corpus root, found from this file rather than from the cwd."""
    return pathlib.Path(__file__).resolve().parent.parent


def _planned(root):
    """The plan, refusing to stand in for one that could not be derived."""
    plan = plan_for(root)
    assert not plan.refusals, (
        UNPLANNABLE + repr([refusal.line() for refusal in plan.refusals])
    )
    return plan


def _records(text):
    """Each status record as (code, path, origin), the origin field consumed."""
    fields = iter([field for field in text.split(chr(0)) if field])
    for field in fields:
        code, where = field[:2], field[3:]
        origin = next(fields, '') if code[0] in WITH_ORIGIN else ''
        yield code, where, origin


def _touched(code, where, origin):
    """Every path one record says an EXISTING file was rewritten, removed or moved at.

    An addition is none of those: R3 forbids moving, renaming and
    rewriting, so a new file reports the same here staged or untracked.
    """
    if code == '??':
        return []
    found = [where] if [letter for letter in code if letter in CHANGED] else []
    return [*found, origin] if code[0] == MOVED else found


def _undeclared(root, plan, touched):
    """Which of `touched` nothing declares: not the plan, the record, or the manifest."""
    files = {where for where in plan.paths if not where.endswith('/')}
    files |= generated(root)
    files |= set(PERMITTED)
    under = (FRAMEWORK_DIR, *(w for w in plan.paths if w.endswith('/')))
    return sorted(
        {
            where
            for where in touched
            if where not in files
            and not [at for at in under if where.startswith(at)]
        }
    )


def test_no_path_a_build_writes_here_is_this_corpus_own_content():
    """R3 from the declaration, so the verdict does not move with the tree."""
    root = _root()
    plan = _planned(root)
    content = parse((root / MANIFEST_FILENAME).read_text(encoding='utf-8')).content
    landing = sorted(
        where
        for where in plan.paths
        if where not in PERMITTED and reads_as_content(where.rstrip('/'), content)
    )
    assert not landing, (
        'generation is additive (R3); a build of this corpus would write over '
        'these paths, which its own manifest reads as content: ' + repr(landing)
    )


def test_the_edits_this_check_was_generated_with_are_still_the_declared_ones():
    """A baked list that drifted from corpus.json checks a corpus that moved on."""
    plan = _planned(_root())

    declared = sorted(edit.path for edit in plan.edits)

    assert declared == sorted(PERMITTED), (
        'this check was generated against permitted_edits that corpus.json no '
        'longer declares; regenerate it rather than editing it (R19): ' +
        repr(declared)
    )


def test_nothing_that_already_existed_changed_but_what_is_declared():
    """R3 in the tree, read through the same declaration and both status letters."""
    root = _root()
    git = shutil.which('git')
    if git is None:
        pytest.skip('git is not installed, so the working tree cannot be read')
    result = subprocess.run(
        [git, 'status', '--porcelain', '-z'],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        pytest.skip('not a git working tree, so there is nothing to compare with')
    touched = [
        where for record in _records(result.stdout) for where in _touched(*record)
    ]

    undeclared = _undeclared(root, _planned(root), touched)

    assert not undeclared, (
        'generation is additive (R3); these files already existed and were '
        'rewritten, removed or moved, and nothing declares them — not this '
        "corpus's permitted_edits, not the plan's output, not the install "
        'record: ' + repr(undeclared)
    )
