"""The framework pin, and the stubs that must agree with it.

⛔ Generated by studyforge onboarding. A hand-edit here is a finding
against that skill rather than a fix (R19); change corpus.json and
regenerate.
"""

from __future__ import annotations

import json
import os
import pathlib
import re
import shutil
import subprocess


PIN = '.studyforge/pin.json'
STUBS = ['.studyforge/skills/reconnaissance.md', '.studyforge/skills/adapter.md', '.studyforge/skills/onboarding.md']
FRAMEWORK = 'studyforge'
GIT_LOCAL_ONLY = {'GIT_NO_LAZY_FETCH': '1', 'GIT_TERMINAL_PROMPT': '0'}
GIT_TIMEOUT = 60


def main_checkout(root: pathlib.Path | str) -> pathlib.Path:
    """Return the checkout the framework stands beside: `root`, or its main checkout.

    ⭐ When `root` is the top level of a LINKED worktree, the answer is the main
    checkout that `--git-common-dir` names (`W286`). ⛔ Anything else — no git,
    no directory, a `root` that is not a checkout's top level, a common
    directory not named `.git` — answers `root` itself, so a plain copy or an
    export stands beside its own parent. ⚠️ Resolved first, because
    `Path(".").parent` is `.` itself. ⛔ Self-contained on purpose: the
    generated pin test carries this function's own source.
    """
    here = pathlib.Path(root).resolve()
    git = shutil.which("git")
    if git is None or not here.is_dir():
        return here

    def ask(*arguments: str) -> str | None:
        done = subprocess.run(
            [git, "-C", str(here), *arguments],
            capture_output=True,
            check=False,
            env={**os.environ, **GIT_LOCAL_ONLY},
            timeout=GIT_TIMEOUT,
        )
        return os.fsdecode(done.stdout).rstrip("\n") if done.returncode == 0 else None

    top = ask("rev-parse", "--show-toplevel")
    if not top or pathlib.Path(top).resolve() != here:
        return here
    common = ask("rev-parse", "--git-common-dir")
    shared = (here / common).resolve() if common else None
    return shared.parent if shared is not None and shared.name == ".git" else here


def _root():
    """The corpus root, found from this file rather than from the cwd."""
    return pathlib.Path(__file__).resolve().parent.parent


def test_the_pin_records_a_commit_and_not_a_path():
    """A pin carrying a path would carry somebody's home directory (R7)."""
    pin = json.loads((_root() / PIN).read_text(encoding='utf-8'))
    assert re.fullmatch('[0-9a-f]{40}', pin['commit']), (
        'the pin records a commit; a path is not one'
    )
    assert pin['where'] == 'sibling', 'the framework is a sibling checkout'


def test_the_framework_beside_this_corpus_holds_the_pinned_commit():
    """A pin naming a commit the framework lacks points at nothing (W270)."""
    pin = json.loads((_root() / PIN).read_text(encoding='utf-8'))
    framework = main_checkout(_root()).parent / FRAMEWORK
    assert framework.is_dir(), (
        'there is no framework checkout beside this corpus, a sibling named ' +
        repr(FRAMEWORK) + ' beside its main checkout (this corpus itself '
        'unless it is a linked worktree), so the pinned commit cannot be checked'
    )
    git = shutil.which('git')
    assert git, 'git is not installed, so the pinned commit cannot be checked'
    env = {**os.environ, **GIT_LOCAL_ONLY}

    def ask(*arguments):
        command = [git, '-C', str(framework), *arguments]
        return subprocess.run(command, capture_output=True, env=env, check=False)

    assert ask('rev-parse', '--git-dir').returncode == 0, (
        'the framework beside this corpus is not a git checkout'
    )
    assert ask('cat-file', '-e', pin['commit'] + '^{commit}').returncode == 0, (
        'the framework checkout beside this corpus does not hold the pinned '
        'commit; regenerate the pin at a commit it has (R19)'
    )


def test_no_stub_has_drifted_from_the_pin():
    """A stub naming another commit is a pointer that aged without saying so."""
    root = _root()
    pin = json.loads((root / PIN).read_text(encoding='utf-8'))
    drifted = []
    for where in STUBS:
        text = (root / where).read_text(encoding='utf-8')
        if ('pin: ' + pin['commit']) not in text:
            drifted.append(where)
    assert not drifted, (
        'these stubs name a commit the pin does not: ' + repr(drifted) +
        '; regenerate them rather than editing them (R19)'
    )


def test_the_framework_is_not_a_submodule():
    """R18, amended: nothing here is pushed, so a submodule URL has no form."""
    assert not (_root() / '.gitmodules').exists(), (
        'the framework is a sibling checkout at a recorded commit, '
        'never a submodule'
    )
